# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: RBA Mimarlık
description: >
  RBA Mimarlık ve Mühendislik Hizmetleri.
baseurl: "" # the subpath of your site, e.g. /blog

email: info@rbamimarlik.com
url: "http://rbamimarlik.com" # the base hostname & protocol for your site
twitter_username: rbamimarlik
linkedin_company: rba-mimarlık
googleplus_username: 107665377844803721309
facebook_page: rbamimarlik

# used for apply button in career page
career_email: jobs@rbamimarlik.com

# Build settings
markdown: kramdown
